apiVersion: apps/v1
kind: Deployment

metadata:
  name: airflow-scheduler
  namespace: crypto-streaming

spec:
  replicas: 1

  selector:
    matchLabels:
      app: airflow-scheduler

  template:
    metadata:
      labels:
        app: airflow-scheduler

    spec:
      containers:
        - name: airflow-scheduler
          image: 504429674609.dkr.ecr.us-east-1.amazonaws.com/crypto-airflow:latest
          imagePullPolicy: Always

          env:
            - name: AIRFLOW__CORE__EXECUTOR
              value: SequentialExecutor

            - name: AIRFLOW__DATABASE__SQL_ALCHEMY_CONN
              value: sqlite:////opt/airflow/airflow.db

            - name: AIRFLOW__CORE__LOAD_EXAMPLES
              value: "false"

            - name: AIRFLOW__WEBSERVER__SECRET_KEY
              value: airflow_secret_key

          command:
            - bash
            - -c
            - |
              airflow db migrate &&
              airflow scheduler