apiVersion: v1
kind: Service

metadata:
  name: crypto-api-service
  namespace: crypto-streaming

spec:
  selector:
    app: crypto-api

  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000

  type: LoadBalancer