apiVersion: v1
kind: PersistentVolumeClaim

metadata:
  name: grafana-data
  namespace: crypto-streaming

spec:
  accessModes:
    - ReadWriteOnce

  storageClassName: gp2

  resources:
    requests:
      storage: 2Gi