apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: crypto-streaming
type: Opaque
stringData:
  POSTGRES_DB: crypto_db
  POSTGRES_USER: crypto_user
  POSTGRES_PASSWORD: crypto_password