apiVersion: apps/v1
kind: Deployment
metadata:
  name: crypto-producer
  namespace: crypto-streaming

spec:
  replicas: 1

  selector:
    matchLabels:
      app: crypto-producer

  template:
    metadata:
      labels:
        app: crypto-producer

    spec:
      containers:
        - name: crypto-producer
          image: 504429674609.dkr.ecr.us-east-1.amazonaws.com/crypto-producer:latest
          imagePullPolicy: Always

          envFrom:
            - configMapRef:
                name: crypto-config