name: Deploy to AWS EKS

on:
  workflow_dispatch:
  push:
    branches:
      - main

env:
  AWS_REGION: eu-west-1
  AWS_ACCOUNT_ID: 504429674609
  EKS_CLUSTER_NAME: crypto-streaming-eks

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build and push API image
        run: |
          docker build -t crypto-api ./api
          docker tag crypto-api:latest $AWS_ACCOUNT_ID.dkr.ecr.us-east-1.amazonaws.com/crypto-api:latest
          docker push $AWS_ACCOUNT_ID.dkr.ecr.us-east-1.amazonaws.com/crypto-api:latest

      - name: Build and push Producer image
        run: |
          docker build -t crypto-producer ./producer
          docker tag crypto-producer:latest $AWS_ACCOUNT_ID.dkr.ecr.us-east-1.amazonaws.com/crypto-producer:latest
          docker push $AWS_ACCOUNT_ID.dkr.ecr.us-east-1.amazonaws.com/crypto-producer:latest

      - name: Build and push Spark image
        run: |
          docker build -t crypto-spark ./streaming
          docker tag crypto-spark:latest $AWS_ACCOUNT_ID.dkr.ecr.us-east-1.amazonaws.com/crypto-spark:latest
          docker push $AWS_ACCOUNT_ID.dkr.ecr.us-east-1.amazonaws.com/crypto-spark:latest

      - name: Build and push Airflow image
        run: |
          docker build -t crypto-airflow ./airflow
          docker tag crypto-airflow:latest $AWS_ACCOUNT_ID.dkr.ecr.us-east-1.amazonaws.com/crypto-airflow:latest
          docker push $AWS_ACCOUNT_ID.dkr.ecr.us-east-1.amazonaws.com/crypto-airflow:latest

      - name: Configure kubectl for EKS
        run: |
          aws eks update-kubeconfig --region $AWS_REGION --name $EKS_CLUSTER_NAME

      - name: Deploy Kubernetes manifests
        run: |
          kubectl apply -f k8s/
          kubectl rollout restart deployment crypto-api -n crypto-streaming
          kubectl rollout restart deployment crypto-producer -n crypto-streaming
          kubectl rollout restart deployment spark-streaming -n crypto-streaming
          kubectl rollout restart deployment airflow-webserver -n crypto-streaming
          kubectl rollout restart deployment airflow-scheduler -n crypto-streaming

      - name: Verify deployment
        run: |
          kubectl get pods -n crypto-streaming
          kubectl get svc -n crypto-streaming